routes/web.php
<?php

use App\Http\Controllers\admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\admin\UrlController as AdminUrlController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\member\ProfileController;
use App\Http\Controllers\member\UrlController;
use App\Http\Controllers\member\VisitorController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('home');

Route::get('/{id}', [UrlController::class, 'redirectTo']);
Route::post('/home/store', [HomeController::class, 'store'])->name('home.store');


Route::group(['middleware' => 'guest'], function () {
    Route::get('/auth/login', [AuthController::class, 'index'])->name('login');
    Route::post('/auth/login', [AuthController::class, 'doLogin'])->name('doLogin');
    Route::get('/auth/register', [AuthController::class, 'register'])->name('register');
    Route::post('/auth/register', [AuthController::class, 'doRegister'])->name('doRegister');
    Route::get('/auth/verify/{link}', [AuthController::class, 'verify'])->name('verify');


    Route::get('/auth/resetVerify/{link}', [AuthController::class, 'resetVerify'])->name('resetVerify');
    Route::get('/auth/reset', [AuthController::class, 'reset'])->name('reset');
    Route::post('/auth/reset', [AuthController::class, 'doReset'])->name('doReset');
    Route::put('/auth/passwordReset', [AuthController::class, 'passwordReset'])->name('passwordReset');
});

Route::group(['middleware' => 'auth'], function () {
    Route::resource('/member/url', UrlController::class);
    Route::resource('/admin/adminUrl', AdminUrlController::class);
    Route::resource('/member/visitor', VisitorController::class);
    Route::get('/member/dashboard', [DashboardController::class, 'index'])->name('member.dashboard.index');
    Route::get('/admin/dashboard', [AdminDashboardController::class, 'index'])->name('admin.dashboard.index');
    Route::get('/member/profile', [ProfileController::class, 'index'])->name('member.profile.index');
    Route::post('/member/profile', [ProfileController::class, 'update'])->name('member.profile.update');
    Route::get('/auth/logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('/member/url/{short}/delete', [UrlController::class, 'delete'])->name('member.urls.delete');
});

app/Http/Controllers/admin/UrlController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UrlController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $urls = DB::table('urls')
            ->select('email', 'full_url', 'short_url', 'urls.created_at as created_at')
            ->join('users', 'users.id', '=', 'urls.user_id', 'left')
            ->paginate('10');
        return view('admin.url.index', ['urls' => $urls]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/member/UrlController.php
<?php

namespace App\Http\Controllers\member;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\URL;
use Jenssegers\Agent\Facades\Agent;

class UrlController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $urls = DB::table('urls')->where('user_id', Auth::id())
            ->paginate('10');
        return view('member.url.index', ['urls' => $urls]);
    }

    static public function hits($short_url)
    {
        $hits = DB::table('visitors')->where('short_url', $short_url)->count();
        return $hits;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'full_url' => 'required|url',
        ]);

        if (!$this->_urlValidator($request->full_url)) {
            return back()->with('error', 'URL tidak valid / url server tujuan Down.');
        }
        $shortUrl = $this->_shortenUrl(4);
        // $shortUlr = 'FdMW';
        $shortUrlRef = DB::table('urls')->where('short_url', $shortUrl)->get();
        // dd($shortUrlRef);
        if (!$shortUrlRef->isEmpty()) {
            return back()->with('error', 'Kami mengalami gangguan, silahkan coba kembali.');
        }

        $is_guest = (Auth::id() == '') ? 1 : 0;
        $data = [
            'user_id' => Auth::id(),
            'full_url' => $request->full_url,
            'short_url' => $shortUrl,
            'is_guest' => $is_guest,
            'created_at' => now(),
            'updated_at' => now()
        ];

        DB::table('urls')->insert($data);
        return back()->with('message', URL::to('') . '/' . $shortUrl);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function delete($id)
    {

        DB::table('urls')->where('short_url', $id)->delete();
        DB::table('visitors')->where('short_url', $id)->delete();
        return back()->with('message', 'Link berhasil dihapus.');
    }

    private function _shortenUrl($limit)
    {
        $shortUlr = '';
        $char = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
        for ($i = 0; $i < $limit; $i++) {
            $index = rand(0, (strlen($char) - 1));
            $shortUlr .= $char[$index];
        }

        return $shortUlr;
    }

    private function _urlValidator($uri)
    {

        try {
            //code...
            $client = Http::get($uri);
            if ($client) {
                return true;
            }
        } catch (\Throwable $th) {
            return false;
        }
    }

    public function redirectTo(Request $request, $short_url)
    {
        $url = DB::table('urls')->where('short_url', $short_url)->first();
        if ($url == NULL) {
            return redirect()->route('home')->with('error', 'Url tidak ditemukan diserver kami.');
        }
        $data = [
            'short_url' => $short_url,
            'ip' => $request->ip(),
            'platform' => Agent::platform(),
            'browser_agent' => Agent::browser(),
            'created_at' => now(),
        ];

        DB::table('visitors')->insert($data);
        return redirect()->away($url->full_url);
    }
}

resources/views/admin/url/index.blade.php
@extends('layouts.admin-master')
@section('page-heading')
    Kelola Url
@endsection

@section('content')
  <div class="row">
    <div class="col col-md-12 col-lg-12">
        <div class="card">
            <div class="card-body table-responsive">
                <table class="table table-bordered table-hover table-md">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>User</th>
                            <th>Full Url</th>
                            <th>Shorten Url</th>
                            <th>Hits</th>
                            <th>Created_at</th>
                            <th>#</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php $no =1 @endphp
                        @php use \App\Http\Controllers\member\UrlController; @endphp
                        @foreach ($urls as $url)
                            <tr>
                                <td>{{$urls ->perPage()*($urls->currentPage()-1)+$no++}}</td>
                                <td>{{$url->email ? $url->email:'guest'}}</td>
                                <td>{{$url->full_url}}</td>
                                <td><a href="{{url('/').'/'.$url->short_url}}" target="_blank" rel="noopener noreferrer">{{url('/').'/'.$url->short_url}}</a></td>
                                <td>{{UrlController::hits($url->short_url)}}</td>
                                <td>{{$url->created_at}}</td>
                                <td class="d-flex">
                                    <a href="{{route('visitor.show', $url->short_url)}}" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="" data-original-title="Lihat Detail"><i class="fas fa-align-center"></i></a>
                                    {{-- <a href="#" class="btn btn-warning btn-sm ml-1""><i class="fas fa-edit"></i></a>--}}
                                    <a href="{{route('member.urls.delete', $url->short_url)}}" class="btn btn-danger btn-sm ml-1"><i class="fas fa-trash"></i></a> 
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="card-body text-right">
                <nav class="d-inline-block">
                  {{$urls->links()}}
                </nav>
            </div>
        </div>
    </div>
  </div>
@endsection