routes/web.php
<?php

use App\Http\Controllers\admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\admin\UrlController as AdminUrlController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\member\ProfileController;
use App\Http\Controllers\member\UrlController;
use App\Http\Controllers\member\VisitorController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('home');

Route::get('/{id}', [UrlController::class, 'redirectTo']);
Route::post('/home/store', [HomeController::class, 'store'])->name('home.store');


Route::group(['middleware' => 'guest'], function () {
    Route::get('/auth/login', [AuthController::class, 'index'])->name('login');
    Route::post('/auth/login', [AuthController::class, 'doLogin'])->name('doLogin');
    Route::get('/auth/register', [AuthController::class, 'register'])->name('register');
    Route::post('/auth/register', [AuthController::class, 'doRegister'])->name('doRegister');
    Route::get('/auth/verify/{link}', [AuthController::class, 'verify'])->name('verify');


    Route::get('/auth/resetVerify/{link}', [AuthController::class, 'resetVerify'])->name('resetVerify');
    Route::get('/auth/reset', [AuthController::class, 'reset'])->name('reset');
    Route::post('/auth/reset', [AuthController::class, 'doReset'])->name('doReset');
    Route::put('/auth/passwordReset', [AuthController::class, 'passwordReset'])->name('passwordReset');
});

Route::group(['middleware' => 'auth'], function () {
    Route::resource('/member/url', UrlController::class);
    Route::resource('/admin/adminUrl', AdminUrlController::class);
    Route::resource('/member/visitor', VisitorController::class);
    Route::get('/member/dashboard', [DashboardController::class, 'index'])->name('member.dashboard.index');
    Route::get('/admin/dashboard', [AdminDashboardController::class, 'index'])->name('admin.dashboard.index');
    Route::get('/member/profile', [ProfileController::class, 'index'])->name('member.profile.index');
    Route::post('/member/profile', [ProfileController::class, 'update'])->name('member.profile.update');
    Route::get('/auth/logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('/member/url/{short}/delete', [UrlController::class, 'delete'])->name('member.urls.delete');
});

resources/views/layouts/admin-master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
<title>@yield('page-heading', 'mbc') &mdash; {{env('APP_NAME')}}</title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  <!-- CSS Libraries -->
  @stack('css-summernote')
  <!-- Template CSS -->
  <link rel="stylesheet" href="{{asset('assets/css/style.css')}}">
  <link rel="stylesheet" href="{{asset('assets/css/components.css')}}">
</head>

<body>
  <div id="app">
    <div class="main-wrapper">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            {{-- <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li> --}}
          </ul>
          {{-- <div class="search-element">
            <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250">
            <button class="btn" type="submit"><i class="fas fa-search"></i></button>
            <div class="search-backdrop"></div>
            <div class="search-result">
              <div class="search-header">
                Histories
              </div>
              <div class="search-item">
                <a href="#">How to hack NASA using CSS</a>
                <a href="#" class="search-close"><i class="fas fa-times"></i></a>
              </div>
              <div class="search-item">
                <a href="#">Kodinger.com</a>
                <a href="#" class="search-close"><i class="fas fa-times"></i></a>
              </div>
              <div class="search-item">
                <a href="#">#Stisla</a>
                <a href="#" class="search-close"><i class="fas fa-times"></i></a>
              </div>
              <div class="search-header">
                Result
              </div>
              <div class="search-item">
                <a href="#">
                <img class="mr-3 rounded" width="30" src="{{asset('assets/img/products/product-3-50.png')}}" alt="product">
                  oPhone S9 Limited Edition
                </a>
              </div>
              <div class="search-item">
                <a href="#">
                  <img class="mr-3 rounded" width="30" src="../assets/img/products/product-2-50.png" alt="product">
                  Drone X2 New Gen-7
                </a>
              </div>
              <div class="search-item">
                <a href="#">
                  <img class="mr-3 rounded" width="30" src="../assets/img/products/product-1-50.png" alt="product">
                  Headphone Blitz
                </a>
              </div>
              <div class="search-header">
                Projects
              </div>
              <div class="search-item">
                <a href="#">
                  <div class="search-icon bg-danger text-white mr-3">
                    <i class="fas fa-code"></i>
                  </div>
                  Stisla Admin Template
                </a>
              </div>
              <div class="search-item">
                <a href="#">
                  <div class="search-icon bg-primary text-white mr-3">
                    <i class="fas fa-laptop"></i>
                  </div>
                  Create a new Homepage Design
                </a>
              </div>
            </div>
          </div> --}}
        </form>
        @include('layouts.topbar')
      </nav>
      @include('layouts.sidebar')

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>@yield('page-heading','Blank Page')</h1>
          </div>

          <div class="section-body">
              @yield('content')
          </div>
        </section>
      </div>
        @stack('modal')
      @include('layouts.footer')
    </div>
  </div>

  <!-- General JS Scripts -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="{{asset('assets/js/stisla.js')}}"></script>

  <!-- JS Libraies -->

  <!-- Template JS File -->
  <script src="{{asset('assets/js/scripts.js')}}"></script>
  <script src="{{asset('assets/js/custom.js')}}"></script>

  <!-- Page Specific JS File -->
  @stack('summernote')
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
      Copyright &copy; 2021 <div class="bullet"></div> {{config('app.name')}} <a href="https://kominfo.singkawangkota.go.id/" target="_blank">{{config('app.dinas')}}</a>
    </div>
    <div class="footer-right">
      V 0.1
    </div>
</footer>

resources/views/layouts/sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
      <div class="sidebar-brand">
      <a href="{{route('member.dashboard.index')}}"><img class="mr-1" src="{{asset('assets/img/logo-skw-150.png')}}" alt="Logo Pemkot Singkawang" srcset="" height="50px">{{env('APP_NAME')}}</a>
      </div>
      <div class="sidebar-brand sidebar-brand-sm">
        <a href="{{route('member.dashboard.index')}}">
          <img src="{{asset('assets/img/logo-skw-150.png')}}" alt="Logo Pemkot Singkawang" srcset="" height="50px">
        </a>
      </div>
      <ul class="sidebar-menu">
          <li class="menu-header">Main Menu</li>
          @can('admin')
          <li><a class="nav-link" href="{{ route('admin.dashboard.index') }}"><i class="fas fa-desktop"></i><span>Dashboard</span></a></li>
          <li><a class="nav-link" href="{{ route('adminUrl.index') }}"><i class="fas fa-globe"></i><span>Kelola URL</span></a></li>
          <li><a class="nav-link" href=""><i class="fas fa-user"></i><span>User</span></a></li>
          
          @elsecan('member')
          <li><a class="nav-link" href="{{ route('member.dashboard.index') }}"><i class="fas fa-desktop"></i><span>Dashboard</span></a></li>
          <li><a class="nav-link" href="{{ route('url.index') }}"><i class="fas fa-globe"></i><span>Kelola URL</span></a></li>
          <li><a class="nav-link" href="{{ route('member.profile.index') }}"><i class="fas fa-user"></i><span>Profile</span></a></li>
          @endcan
          </li>
        </ul>
        <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
          <a href="{{ route('logout') }}" class="btn btn-danger btn-lg btn-block btn-icon-split">
            <i class="fas fa-sign-out-alt"></i> Logout
          </a>
        </div>
    </aside>
</div>

resources/views/layouts/topbar.blade.php
@php
    $carbon = new Carbon\Carbon;
@endphp
<ul class="navbar-nav navbar-right">
    <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
    <img alt="image" src="{{asset('assets/img/avatar/avatar-1.png')}}" class="rounded-circle mr-1">
      <div class="d-sm-none d-lg-inline-block">Hi, {{ (auth()->user()) ? auth()->user()->name : ''}}</div></a>
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-title">Login {{$carbon->diffForHumans(session('login_time'))}}</div>
        <div class="dropdown-divider"></div>
        <a href="{{ route('logout') }}" class="dropdown-item has-icon text-danger">
          <i class="fas fa-sign-out-alt"></i> Logout
        </a>
      </div>
    </li>
  </ul>